# Generated by Django 4.2.11 on 2025-02-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_image_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='uploadimage',
        ),
    ]
